/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.Banca;
import ec.ups.edu.controlador.ControladorPersona;
import ec.ups.edu.controlador.Descuento;
import ec.ups.edu.controlador.JuegoClasico;
import ec.ups.edu.controlador.JuegoParImpar;
import ec.ups.edu.controlador.Mesa;
import ec.ups.edu.controlador.MesaParImpar;
import ec.ups.edu.modelo.Persona;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class VentanaJuegoParImpar extends javax.swing.JInternalFrame {

    Banca banco;

    int numeroRuleta;
    Descuento descuento = new Descuento();
    ControladorPersona controladorPersona;
    MesaParImpar mesaParImpar;
    List<JuegoParImpar> lista;

    public VentanaJuegoParImpar() {
        initComponents();

        banco = new Banca();
        controladorPersona = new ControladorPersona();
        lista = new ArrayList<>();
        lista.add(null);
        lista.add(null);
        lista.add(null);
        lista.add(null);

        lblcliente1.setVisible(false);
        lblcliente2.setVisible(false);
        lblcliente3.setVisible(false);
        lblcliente4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnRetirar3 = new javax.swing.JButton();
        btnAgregar4 = new javax.swing.JButton();
        btnRetirar4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblcliente1 = new javax.swing.JLabel();
        lblcliente2 = new javax.swing.JLabel();
        lblcliente3 = new javax.swing.JLabel();
        lblcliente4 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        btnRetirar1 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        btnRetirar2 = new javax.swing.JButton();
        btnAgregar3 = new javax.swing.JButton();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumero3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("JUEGO PAR IMPAR");

        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnRetirar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        btnRetirar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar3ActionPerformed(evt);
            }
        });

        btnAgregar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btnAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar4ActionPerformed(evt);
            }
        });

        btnRetirar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        btnRetirar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar4ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(0, 4));

        lblcliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador.png"))); // NOI18N
        jPanel2.add(lblcliente1);

        lblcliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador.png"))); // NOI18N
        jPanel2.add(lblcliente2);

        lblcliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador.png"))); // NOI18N
        jPanel2.add(lblcliente3);

        lblcliente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugador.png"))); // NOI18N
        jPanel2.add(lblcliente4);

        jScrollPane3.setViewportView(jPanel2);

        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnRetirar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        btnRetirar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar1ActionPerformed(evt);
            }
        });

        btnAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnRetirar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        btnRetirar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar2ActionPerformed(evt);
            }
        });

        btnAgregar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero jugado");

        jLabel5.setText("Numero jugado");

        jLabel4.setText("Numero jugado");

        jLabel7.setText("Numero jugado");

        jLabel2.setText("Numero mesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnEmpezar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRetirar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmpezar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetirar1)
                            .addComponent(btnAgregar1)
                            .addComponent(btnRetirar2)
                            .addComponent(btnAgregar2)
                            .addComponent(btnRetirar3)
                            .addComponent(btnAgregar3)
                            .addComponent(btnRetirar4)
                            .addComponent(btnAgregar4))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getNumeroRuleta() {
        return numeroRuleta;
    }

    public void setNumeroRuleta(int numeroRuleta) {
        this.numeroRuleta = numeroRuleta;
    }

    public int sacarNumero() {

        setNumeroRuleta((int) (Math.random() * 36));
        return getNumeroRuleta();

    }


    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed

        mesaParImpar = new MesaParImpar(lista, txtNumeroMesa);


    }//GEN-LAST:event_btnEmpezarActionPerformed

    /*   public void creacionHilos() {

        int creacionHilo = 1;
        JuegoParImpar jpi[] = new JuegoParImpar[creacionHilo];

        int numRuleta = sacarNumero();
        int cont = 0;
        boolean iniciar = true;

        for (int i = 0; i < creacionHilo; i++) {

            jpi[i] = new JuegoParImpar(banco);

        }

        while (iniciar) {

            txtNumero1.setText(numRuleta + "");
            txtArea.append(cont + "----------numero Ruleta  " + numRuleta + "\n");
            System.out.println(cont + "----------numero Ruleta  " + numRuleta);

            if (numRuleta != 0) {
                try {
                    for (int i = 0; i < creacionHilo; i++) {

                        jpi[i].setNumeroAzar(numRuleta);

                        Thread th = new Thread(jpi[i]);

                        th.setName("Hilo " + i + " ParImpar ");
                        //txtArea.append("Hilo " + i + " numeroConcreto");

                        th.start();

                    }

                    cont++;
                    //Llamamos al metodo sleep para que se imprima la cuantia del banco justo despues de que se ejecuten los hilos
                    Thread.sleep(50);
                    System.out.println("BANCO: " + banco.getDineroBanco());
                    txtArea.append("BANCO: " + banco.getDineroBanco() + "\n");
                    //Volvem    os a utilizar el metodo sleep como se pide en el enunciado
                    Thread.sleep(2000);
                    //Sacamos otro numero pasados esos 2 segundos
                    numRuleta = sacarNumero();
                } catch (InterruptedException ex) {
                    Logger.getLogger(VentanaJugadorClasico.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                iniciar = false;
            }

            System.out.println("Partida terminada el numero es cero");
            txtArea.setText("Partida terminada el numero es cero");
        }

    }*/

    private void btnAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar4ActionPerformed

        
        String ingreso = JOptionPane.showInputDialog("Ingrese el numero de cedula de la puerca");

        if (ingreso.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Llene el campo");

        } else {
            Persona persona = controladorPersona.buscar(ingreso);

            if (persona != null) {

                
                lista.set(0, new JuegoParImpar(banco, descuento, persona, txtArea, txtNumero4));
                lblcliente4.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(this, "no existe un jugador con el numero de cedula " + ingreso);

            }

        }
        
        

    }//GEN-LAST:event_btnAgregar4ActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed

        String ingreso = JOptionPane.showInputDialog("Ingrese el numero de cedula ");

        if (ingreso.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Llene el campo");

        } else {

            Persona p = controladorPersona.buscar(ingreso);

            if (p != null) {

                lista.set(0, new JuegoParImpar(banco, descuento, p, txtArea, txtNumero1));
                lblcliente1.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(this, "no existe un jugador con el numero de cedula " + ingreso);

            }

        }

        

    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed

        lblcliente2.setVisible(true);
        
        String ingreso = JOptionPane.showInputDialog("Ingrese el numero de cedula ");

        if (ingreso.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Llene el campo");

        } else {
            Persona persona = controladorPersona.buscar(ingreso);

            if (persona != null) {

                
                lista.set(0, new JuegoParImpar(banco, descuento, persona, txtArea, txtNumero2));
                lblcliente2.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(this, "no existe un jugador con el numero de cedula " + ingreso);

            }

        }
        
        
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed

        
        String ingreso = JOptionPane.showInputDialog("Ingrese el numero de cedula ");

        if (ingreso.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Llene el campo");

        } else {
            Persona persona = controladorPersona.buscar(ingreso);

            if (persona != null) {

                
                lista.set(0, new JuegoParImpar(banco, descuento, persona, txtArea, txtNumero3));
                lblcliente3.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(this, "no existe un jugador con el numero de cedula " + ingreso);

            }

        }
        
        lblcliente3.setVisible(true);

    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnRetirar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar1ActionPerformed

        lblcliente1.setVisible(false);

    }//GEN-LAST:event_btnRetirar1ActionPerformed

    private void btnRetirar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar2ActionPerformed

        lblcliente2.setVisible(false);

    }//GEN-LAST:event_btnRetirar2ActionPerformed

    private void btnRetirar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar3ActionPerformed

        lblcliente3.setVisible(false);

    }//GEN-LAST:event_btnRetirar3ActionPerformed

    private void btnRetirar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar4ActionPerformed

        lblcliente4.setVisible(false);

    }//GEN-LAST:event_btnRetirar4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnRetirar1;
    private javax.swing.JButton btnRetirar2;
    private javax.swing.JButton btnRetirar3;
    private javax.swing.JButton btnRetirar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcliente1;
    private javax.swing.JLabel lblcliente2;
    private javax.swing.JLabel lblcliente3;
    private javax.swing.JLabel lblcliente4;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    private javax.swing.JTextField txtNumeroMesa;
    // End of variables declaration//GEN-END:variables
}
