/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

/**
 *
 * @author santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    VentanaJugadorClasico ventanaJugador;
    VentanaRegistrarJugador ventanaRegistrarJugador;
    VentanaJuegoParImpar ventanaParImpar;
    VentanaJuegoMartingala ventanJuegoMartingala;
    VentanaRegistros ventanaRegistro;
    
    public VentanaPrincipal() {
        initComponents();
        
        ventanaJugador = new VentanaJugadorClasico();
        ventanaRegistrarJugador = new VentanaRegistrarJugador();
        ventanaParImpar = new VentanaJuegoParImpar();
        ventanJuegoMartingala = new VentanaJuegoMartingala();
        ventanaRegistro = new VentanaRegistros();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemRegistrarJugador = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        itemParImpar = new javax.swing.JMenuItem();
        itemMartingala = new javax.swing.JMenuItem();
        itemRegistros = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText(" Inicio");

        itemRegistrarJugador.setMnemonic('o');
        itemRegistrarJugador.setText("Registrar jugador");
        itemRegistrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarJugadorActionPerformed(evt);
            }
        });
        fileMenu.add(itemRegistrarJugador);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("juego clasico");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        itemParImpar.setMnemonic('s');
        itemParImpar.setText("juego par/Impar");
        itemParImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemParImparActionPerformed(evt);
            }
        });
        fileMenu.add(itemParImpar);

        itemMartingala.setMnemonic('a');
        itemMartingala.setText("juego martingala");
        itemMartingala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMartingalaActionPerformed(evt);
            }
        });
        fileMenu.add(itemMartingala);

        itemRegistros.setMnemonic('a');
        itemRegistros.setText(" Registros");
        itemRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrosActionPerformed(evt);
            }
        });
        fileMenu.add(itemRegistros);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        
        desktopPane.add(ventanaJugador);
        ventanaJugador.setVisible(true);
        
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void itemRegistrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarJugadorActionPerformed

        desktopPane.add(ventanaRegistrarJugador);
        ventanaRegistrarJugador.setVisible(true);
       
    }//GEN-LAST:event_itemRegistrarJugadorActionPerformed

    private void itemParImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemParImparActionPerformed
        
        desktopPane.add(ventanaParImpar);
        ventanaParImpar.setVisible(true);
        
    }//GEN-LAST:event_itemParImparActionPerformed

    private void itemMartingalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMartingalaActionPerformed
        
        desktopPane.add(ventanJuegoMartingala);
        ventanJuegoMartingala.setVisible(true);
        
    }//GEN-LAST:event_itemMartingalaActionPerformed

    private void itemRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrosActionPerformed
        
        desktopPane.add(ventanaRegistro);
        ventanaRegistro.setVisible(true);
        
    }//GEN-LAST:event_itemRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemMartingala;
    private javax.swing.JMenuItem itemParImpar;
    private javax.swing.JMenuItem itemRegistrarJugador;
    private javax.swing.JMenuItem itemRegistros;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
